# Generated by Django 4.2.11 on 2024-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='gallery')),
                ('actors', models.CharField(blank=True, max_length=250)),
                ('release_date', models.DateField()),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
